import { Profile, SkillItem, Wallet, Offer, SessionLeg, ChatMessage } from '@/types';

export const SKILL_TAXONOMY: SkillItem[] = [
  { id: 'sk-py', name: 'Python Programming', category: 'Software & Tech', minHourlyRate: 30, maxHourlyRate: 150 },
  { id: 'sk-rust', name: 'Rust & Systems Design', category: 'Software & Tech', minHourlyRate: 50, maxHourlyRate: 200 },
  { id: 'sk-ui', name: 'UI/UX Design (Figma)', category: 'Design & Creative', minHourlyRate: 25, maxHourlyRate: 120 },
  { id: 'sk-excel', name: 'Advanced Excel & VBA', category: 'Business & Finance', minHourlyRate: 20, maxHourlyRate: 90 },
  { id: 'sk-guitar', name: 'Acoustic Guitar', category: 'Music & Arts', minHourlyRate: 20, maxHourlyRate: 80 },
  { id: 'sk-spanish', name: 'Conversational Spanish', category: 'Languages', minHourlyRate: 25, maxHourlyRate: 100 },
  { id: 'sk-speak', name: 'Public Speaking & Pitching', category: 'Personal Growth', minHourlyRate: 35, maxHourlyRate: 140 },
  { id: 'sk-finance', name: 'Financial Modeling', category: 'Business & Finance', minHourlyRate: 40, maxHourlyRate: 180 },
];

export const CURRENT_USER: Profile = {
  id: 'usr-asha',
  email: 'asha.sharma@example.com',
  fullName: 'Asha Sharma',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Product Designer with 4 years of experience. Passionate about turning complex systems into clean interfaces. Eager to master backend scripting in Python!',
  city: 'Bengaluru',
  country: 'IN',
  timezone: 'Asia/Kolkata',
  languages: ['English', 'Hindi'],
  phoneNumber: '+91 98765 43210',
  phoneVerified: true,
  isOnboarded: true,
  isAcceptingRequests: true,
  strikesCount: 0,
  reputationScore: 4.96,
  completedSessionsCount: 14,
  teachSkills: [
    {
      skillId: 'sk-ui',
      skillName: 'UI/UX Design (Figma)',
      category: 'Design & Creative',
      level: 'expert',
      yearsExperience: 4,
      hourlyRate: 60,
      allowedDurations: [30, 45, 60],
      isVerified: true,
    },
    {
      skillId: 'sk-excel',
      skillName: 'Advanced Excel & VBA',
      category: 'Business & Finance',
      level: 'advanced',
      yearsExperience: 3,
      hourlyRate: 40,
      allowedDurations: [30, 60],
      isVerified: false,
    },
  ],
  learnSkills: [
    {
      skillId: 'sk-py',
      skillName: 'Python Programming',
      category: 'Software & Tech',
      targetLevel: 'intermediate',
      goal: 'Build automated data scraping pipelines and basic FastAPI backends',
    },
    {
      skillId: 'sk-spanish',
      skillName: 'Conversational Spanish',
      category: 'Languages',
      targetLevel: 'beginner',
      goal: 'Travel fluency for upcoming South America trip',
    },
  ],
  availability: {
    Mon: ['18:00-21:00'],
    Tue: ['19:00-21:00'],
    Thu: ['18:00-21:00'],
    Sat: ['10:00-14:00'],
  },
};

export const INITIAL_TEACHERS: Profile[] = [
  {
    id: 'usr-ravi',
    email: 'ravi.k@example.com',
    fullName: 'Ravi Kumar',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Senior Backend Engineer. Writes Python & Go daily. Also love playing fingerstyle acoustic guitar. Wanting to learn UI/UX design to build my own indie apps!',
    city: 'Pune',
    country: 'IN',
    timezone: 'Asia/Kolkata',
    languages: ['English', 'Hindi', 'Marathi'],
    phoneNumber: '+91 91234 56780',
    phoneVerified: true,
    isOnboarded: true,
    isAcceptingRequests: true,
    strikesCount: 0,
    reputationScore: 4.98,
    completedSessionsCount: 28,
    teachSkills: [
      {
        skillId: 'sk-py',
        skillName: 'Python Programming',
        category: 'Software & Tech',
        level: 'expert',
        yearsExperience: 6,
        hourlyRate: 60,
        allowedDurations: [30, 45, 60, 90],
        isVerified: true,
      },
      {
        skillId: 'sk-guitar',
        skillName: 'Acoustic Guitar',
        category: 'Music & Arts',
        level: 'intermediate',
        yearsExperience: 4,
        hourlyRate: 35,
        allowedDurations: [45, 60],
        isVerified: false,
      },
    ],
    learnSkills: [
      {
        skillId: 'sk-ui',
        skillName: 'UI/UX Design (Figma)',
        category: 'Design & Creative',
        targetLevel: 'intermediate',
        goal: 'Design a clean SaaS dashboard without hiring a freelancer',
      },
    ],
    availability: {
      Tue: ['18:00-21:00'],
      Thu: ['19:00-21:00'],
      Sat: ['11:00-16:00'],
    },
  },
  {
    id: 'usr-sofia',
    email: 'sofia.r@example.com',
    fullName: 'Sofia Rodriguez',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    bio: 'Native Spanish speaker living in Mumbai. Language instructor for 5+ years. Looking to master Advanced Excel to optimize my business finances.',
    city: 'Mumbai',
    country: 'IN',
    timezone: 'Asia/Kolkata',
    languages: ['English', 'Spanish'],
    phoneVerified: true,
    isOnboarded: true,
    isAcceptingRequests: true,
    strikesCount: 0,
    reputationScore: 4.92,
    completedSessionsCount: 42,
    teachSkills: [
      {
        skillId: 'sk-spanish',
        skillName: 'Conversational Spanish',
        category: 'Languages',
        level: 'expert',
        yearsExperience: 5,
        hourlyRate: 50,
        allowedDurations: [30, 60],
        isVerified: true,
      },
    ],
    learnSkills: [
      {
        skillId: 'sk-excel',
        skillName: 'Advanced Excel & VBA',
        category: 'Business & Finance',
        targetLevel: 'advanced',
        goal: 'Automate invoice tracking and financial dashboards in Excel',
      },
    ],
    availability: {
      Mon: ['17:00-20:00'],
      Wed: ['17:00-20:00'],
      Fri: ['16:00-19:00'],
    },
  },
  {
    id: 'usr-vikram',
    email: 'vikram.s@example.com',
    fullName: 'Dr. Vikram Seth',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    bio: 'Distributed Systems Architect & ex-Research Fellow. Deep expertise in Rust, async concurrency, and low-latency storage engines.',
    city: 'Hyderabad',
    country: 'IN',
    timezone: 'Asia/Kolkata',
    languages: ['English'],
    phoneVerified: true,
    isOnboarded: true,
    isAcceptingRequests: true,
    strikesCount: 0,
    reputationScore: 5.00,
    completedSessionsCount: 31,
    teachSkills: [
      {
        skillId: 'sk-rust',
        skillName: 'Rust & Systems Design',
        category: 'Software & Tech',
        level: 'expert',
        yearsExperience: 8,
        hourlyRate: 120,
        allowedDurations: [60, 90],
        isVerified: true,
      },
    ],
    learnSkills: [
      {
        skillId: 'sk-guitar',
        skillName: 'Acoustic Guitar',
        category: 'Music & Arts',
        targetLevel: 'beginner',
        goal: 'Learn basic chords for acoustic relaxation on weekends',
      },
    ],
    availability: {
      Sat: ['14:00-18:00'],
      Sun: ['10:00-14:00'],
    },
  },
  {
    id: 'usr-priya',
    email: 'priya.n@example.com',
    fullName: 'Priya Nair',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    bio: 'TEDx speaker and Communications Coach. I help engineers and founders command a room, articulate vision, and nail high-stakes pitches.',
    city: 'Delhi',
    country: 'IN',
    timezone: 'Asia/Kolkata',
    languages: ['English', 'Hindi', 'Malayalam'],
    phoneVerified: true,
    isOnboarded: true,
    isAcceptingRequests: true,
    strikesCount: 0,
    reputationScore: 4.89,
    completedSessionsCount: 19,
    teachSkills: [
      {
        skillId: 'sk-speak',
        skillName: 'Public Speaking & Pitching',
        category: 'Personal Growth',
        level: 'expert',
        yearsExperience: 7,
        hourlyRate: 75,
        allowedDurations: [45, 60],
        isVerified: true,
      },
    ],
    learnSkills: [
      {
        skillId: 'sk-py',
        skillName: 'Python Programming',
        category: 'Software & Tech',
        targetLevel: 'beginner',
        goal: 'Learn data analysis to understand marketing metrics',
      },
    ],
    availability: {
      Tue: ['17:00-20:00'],
      Wed: ['17:00-20:00'],
      Thu: ['17:00-20:00'],
    },
  },
];

export const INITIAL_WALLET: Wallet = {
  userId: 'usr-asha',
  availablePaise: 18000, // 180 Tokens
  heldPaise: 1800,       // 18 Tokens held for active offer
  lifetimeEarnedPaise: 54000, // 540 Tokens earned
  lifetimeSpentPaise: 36000,  // 360 Tokens spent
};

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off-101',
    type: 'SWAP',
    proposerId: 'usr-asha',
    proposerName: 'Asha Sharma',
    recipientId: 'usr-ravi',
    recipientName: 'Ravi Kumar',
    status: 'ACCEPTED',
    message: 'Hey Ravi! I saw you want to level up your UI/UX in Figma. I can teach you Figma prototyping if you help me with Python async and web scraping!',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    expiresAt: new Date(Date.now() + 3600000 * 44).toISOString(),
    quote: {
      type: 'SWAP',
      swapFactor: 0.30,
      proposerLeg: {
        skillId: 'sk-py',
        skillName: 'Python Programming',
        teacherId: 'usr-ravi',
        learnerId: 'usr-asha',
        durationMinutes: 60,
        hourlyRate: 60,
        listPriceTokens: 60,
        chargedTokens: 18, // 70% discount
        platformFeeTokens: 1.8,
        teacherPayoutTokens: 16.2,
      },
      recipientLeg: {
        skillId: 'sk-ui',
        skillName: 'UI/UX Design (Figma)',
        teacherId: 'usr-asha',
        learnerId: 'usr-ravi',
        durationMinutes: 60,
        hourlyRate: 60,
        listPriceTokens: 60,
        chargedTokens: 18,
        platformFeeTokens: 1.8,
        teacherPayoutTokens: 16.2,
      },
      inKindExchangedValue: 60,
      proposerSavingsPct: 70,
      expiresAt: new Date(Date.now() + 3600000 * 24).toISOString(),
    },
  },
];

export const INITIAL_SESSIONS: SessionLeg[] = [
  {
    id: 'ses-201',
    offerId: 'off-101',
    legIndex: 1,
    teacherId: 'usr-ravi',
    teacherName: 'Ravi Kumar',
    learnerId: 'usr-asha',
    learnerName: 'Asha Sharma',
    skillName: 'Python Programming (Async & Scraping)',
    durationMinutes: 60,
    chargedTokens: 18,
    platformFeeTokens: 1.8,
    teacherPayoutTokens: 16.2,
    scheduledStart: new Date(Date.now() + 3600000 * 2).toISOString(), // in 2 hours
    scheduledEnd: new Date(Date.now() + 3600000 * 3).toISOString(),
    meetLink: 'https://meet.google.com/new',
    status: 'SCHEDULED',
    teacherConfirmed: false,
    learnerConfirmed: false,
  },
  {
    id: 'ses-202',
    offerId: 'off-101',
    legIndex: 2,
    teacherId: 'usr-asha',
    teacherName: 'Asha Sharma',
    learnerId: 'usr-ravi',
    learnerName: 'Ravi Kumar',
    skillName: 'UI/UX Design (Figma Components & Auto-layout)',
    durationMinutes: 60,
    chargedTokens: 18,
    platformFeeTokens: 1.8,
    teacherPayoutTokens: 16.2,
    scheduledStart: new Date(Date.now() + 3600000 * 26).toISOString(), // tomorrow
    scheduledEnd: new Date(Date.now() + 3600000 * 27).toISOString(),
    meetLink: 'https://meet.google.com/new',
    status: 'SCHEDULED',
    teacherConfirmed: false,
    learnerConfirmed: false,
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    threadId: 'off-101',
    senderId: 'usr-asha',
    senderName: 'Asha Sharma',
    content: "Hi Ravi! Excited to swap skills. I've prepared a Figma starter kit for your indie app project.",
    timestamp: '14:20',
    type: 'TEXT',
  },
  {
    id: 'msg-2',
    threadId: 'off-101',
    senderId: 'usr-ravi',
    senderName: 'Ravi Kumar',
    content: 'Awesome Asha! I set up our Python environment and wrote a few boilerplate scrapers for our first leg.',
    timestamp: '14:25',
    type: 'TEXT',
  },
  {
    id: 'msg-3',
    threadId: 'off-101',
    senderId: 'usr-ravi',
    senderName: 'Ravi Kumar',
    content: 'Proposed time for Leg 1: Python Programming',
    timestamp: '14:28',
    type: 'PROPOSE_TIME',
    metadata: {
      proposedDate: 'Today',
      proposedTime: '18:00 - 19:00 IST',
      durationMinutes: 60,
      legIndex: 1,
      meetLink: 'https://meet.google.com/new',
    },
  },
  {
    id: 'msg-4',
    threadId: 'off-101',
    senderId: 'usr-asha',
    senderName: 'Asha Sharma',
    content: 'Time accepted! Google Meet link has been generated and calendar invites dispatched.',
    timestamp: '14:30',
    type: 'TIME_CONFIRMED',
    metadata: {
      meetLink: 'https://meet.google.com/new',
    },
  },
];
